modLoader = "javafml"
loaderVersion = "[2,)"
license = "All Rights Reserved"

[[mods]]
modId="disenchantanvil"
version="1.0.0"
displayName="Disenchant Anvil"
description='''  
Allows you to transfer enchantments from items to books using the anvil.  
'''

[[dependencies.disenchantanvil]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.disenchantanvil]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"